name: Publish 2 PSGallery

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Publish
        run: |
          Publish-Module -Path ./SCEPman -NuGetApiKey ${{secrets.PSGalleryAPIKey}}
        shell: pwsh