
name: Test in Lab

# Controls when the action will run. Workflow runs for production and beta version pushes
on:
  push:
    branches:
      - production
      - beta
      - main
    Schedule: 
      -cron: '10 1 * * 0'

# The Test requires an AAD App Registration whose Service Principal has permissions to create apps and assign role assignments as well as read and write the SCEPman Azure resources under test. Specifically:
# - Contributor permissions on the SCEPman resource group
# - Application Administrator role in AAD to create and delete app registrations
# - Privileged Role Administrator to assign Role Assignments to the newly created app registrations
jobs:
  test-run:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    environment: AzureLab
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in with Azure
        if: ${{ !env.ACT }}
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Complete SCEPman installation in PowerShell
        shell: pwsh
        run: |
          cd SCEPman
          Import-Module ./SCEPman.psd1
          $RandomAppRegNumber = Get-Random
          Complete-SCEPmanInstallation -SCEPmanAppServiceName ${{ vars.APP_SERVICE_NAME }} -AzureADAppNameForSCEPman "scepman-api-ghtest-$RandomAppRegNumber" -AzureADAppNameForCertMaster "scepman-certmaster-ghtest-$RandomAppRegNumber" -Verbose 6>&1
          $scepmanappid = az ad app list --display-name "scepman-api-ghtest-$RandomAppRegNumber" -o tsv --query "[].id"
          az ad app delete --id $scepmanappid
          $certmasterappid = az ad app list --display-name "scepman-certmaster-ghtest-$RandomAppRegNumber" -o tsv --query "[].id"
          az ad app delete --id $certmasterappid